### PR TITLE
CAM-5632

### PR DESCRIPTION
**Pull request by berndruecker**
Added possibility to use embedded form from deployment in tasklist
fixes https://app.camunda.com/jira/browse/CAM-5632

You might combine all code changes in one new commit

### CODE REVIEW

**Comment by berndruecker** [comment]
PS:  I will send a seperate PR for the docs

**Comment by martinschimak** [comment]
+1

**Comment by SebastianStamm** [comment]
Hi Bernd,

thanks for the Pull Request :-)

Unfortunately, I can not merge it in the current status because of the following problems:

1. It breaks existing form-keys using a pattern like "embedded:http://example.com/form.html". Instead of loading the form, it is stuck on the "loading" screen

2. If the form key refers to a resource that is not available (e.g. because of a typo in the file name or in the form key), there is no error message. Instead, it is stuck on the "loading" screen.

Could you fix these issues in your PR? Let me know if you need any help.

Cheers
Sebastian

**Comment by berndruecker** [comment]
Hi Sebastian.

Thanks for the review and feedback. I fixed both problems and added test cases for them in pa4, see https://github.com/camunda/camunda-bpm-webapp/pull/6/commits/6c09c5ad8f9d8258431277754eef22e0035cf43c. Please have a look again!

Thanks and cheers
Bernd

**Comment by SebastianStamm** [comment]
Hi Bernd,

looks good :) The only thing I added is a break in the deployment files loop when the resource is found. Merged with eb0f1c0.

Thanks again for contributing!

**Comment by berndruecker** [comment]
Thanks for reviewing and merging :-)

**Pull request closed without merging**
