### PR TITLE
create webjar for embedded usage

### PR DESCRIPTION
**Pull request by jangalinski**
This is related to https://github.com/camunda/camunda-bpm-spring-boot-starter/issues/3 where we need a webjar for spring-boot. 

I used zapatas gradle job as a template to create my jar file.

I am confused though, because the jar I create is much smaller than the jar zapatas build creates. When I checked the content, I found out that in my approach there are no views included. Then I checked the 7.4.0-SNAPSHOT war file content and there are no views either. So maybe this is not an error? Would be glad if someone could check this.

### CODE REVIEW

**Comment by meyerdan** [comment]
Hi Jan, thank you for the pull request.

We will look into it and merge it.

**Comment by meyerdan** [comment]
How can I solve this:

```bash
[INFO] ------------------------------------------------------------------------
[INFO] Building camunda BPM - webapp - webjar 7.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://app.camunda.com/nexus/content/groups/internal/org/camunda/bpm/webapp/camunda-webapp/7.4.0-SNAPSHOT/camunda-webapp-7.4.0-SNAPSHOT-classes.war
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] camunda BPM - webapp - root ....................... SUCCESS [0.424s]
[INFO] camunda BPM - webapp - core ....................... SUCCESS [32.297s]
[INFO] camunda BPM - webapp - test-utility ............... SUCCESS [0.136s]
[INFO] camunda BPM - webapp - app ........................ SUCCESS [6:42.793s]
[INFO] camunda BPM - webapp - webjar ..................... FAILURE [0.376s]
[INFO] camunda BPM - webapp - JBoss ...................... SKIPPED
[INFO] camunda BPM - webapp - JBoss Standalone ........... SKIPPED
[INFO] camunda BPM - webapp - Tomcat ..................... SKIPPED
[INFO] camunda BPM - webapp - Tomcat Standalone .......... SKIPPED
[INFO] camunda BPM - webapp - Glassfish .................. SKIPPED
[INFO] camunda BPM - webapp - Glassfish Standalone ....... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7:17.851s
[INFO] Finished at: Fri Sep 11 12:30:15 CEST 2015
[INFO] Final Memory: 35M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project camunda-webapp-webjar: Could not resolve dependencies for project org.camunda.bpm.webapp:camunda-webapp-webjar:jar:7.4.0-SNAPSHOT: Could not find artifact org.camunda.bpm.webapp:camunda-webapp:war:classes:7.4.0-SNAPSHOT in camunda-nexus (https://app.camunda.com/nexus/content/groups/internal) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :camunda-webapp-webjar
```

**Comment by jangalinski** [comment]
try to remove the <classifier>classes</classifier>   I might have been too tired yesterday ...

I guess we do not need the dependency at all, but I kept it to prevent execution of the webjar module before the webapp module.

**Comment by jangalinski** [comment]
Please also check why the view files are missing ...

**Comment by meyerdan** [comment]
Hi Jan, after fixing the classes thing, I could build the jar.

this is what it contains:

```
meyerd@ca-meyerd:~/Documents/Workspace/camunda-bpm-webapp/webjar/target$ unzip -l camunda-webapp-webjar-7.4.0-SNAPSHOT.jar 
Archive:  camunda-webapp-webjar-7.4.0-SNAPSHOT.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2015-09-11 13:05   META-INF/
      320  2015-09-11 13:05   META-INF/MANIFEST.MF
        0  2015-09-11 12:30   plugin/
        0  2015-09-11 12:30   plugin/decisionList/
        0  2015-09-11 12:30   plugin/decisionList/app/
        0  2015-09-11 12:30   plugin/standaloneTask/
        0  2015-09-11 12:30   plugin/standaloneTask/app/
        0  2015-09-11 12:30   plugin/base/
        0  2015-09-11 12:30   plugin/base/app/
        0  2015-09-11 12:30   plugin/jobDefinition/
        0  2015-09-11 12:30   plugin/jobDefinition/app/
        0  2015-09-11 12:30   app/
        0  2015-09-11 12:30   app/admin/
        0  2015-09-11 12:30   app/admin/fonts/
        0  2015-09-11 12:30   app/admin/styles/
        0  2015-09-11 12:30   app/admin/scripts/
        0  2015-09-11 12:30   app/admin/assets/
        0  2015-09-11 12:30   app/admin/assets/images/
        0  2015-09-11 13:05   app/tasklist/
        0  2015-09-11 12:30   app/tasklist/locales/
        0  2015-09-11 13:05   app/tasklist/fonts/
        0  2015-09-11 12:30   app/tasklist/fonts/bootstrap/
        0  2015-09-11 13:05   app/tasklist/styles/
        0  2015-09-11 13:05   app/tasklist/scripts/
        0  2015-09-11 13:05   app/tasklist/images/
        0  2015-09-11 13:05   app/cockpit/
        0  2015-09-11 13:05   app/cockpit/fonts/
        0  2015-09-11 13:05   app/cockpit/styles/
        0  2015-09-11 13:05   app/cockpit/scripts/
        0  2015-09-11 12:30   app/cockpit/assets/
        0  2015-09-11 13:05   app/cockpit/assets/images/
     1107  2014-07-01 17:20   securityFilterRules.json
    10370  2015-09-11 12:28   plugin/decisionList/app/plugin.js.map
     4936  2015-09-11 12:28   plugin/decisionList/app/plugin.js
     9496  2015-09-11 12:28   plugin/standaloneTask/app/plugin.js.map
     4734  2015-09-11 12:28   plugin/standaloneTask/app/plugin.js
   203718  2015-09-11 12:28   plugin/base/app/plugin.js.map
    97026  2015-09-11 12:28   plugin/base/app/plugin.js
    62594  2015-09-11 12:28   plugin/jobDefinition/app/plugin.js.map
    35225  2015-09-11 12:28   plugin/jobDefinition/app/plugin.js
      240  2015-01-14 14:10   index.html
   117868  2015-09-11 12:29   app/admin/fonts/opensans-regular-webfont.svg
    46864  2015-09-11 12:29   app/admin/fonts/opensans-bold-webfont.ttf
    21925  2015-09-11 12:29   app/admin/fonts/opensans-bold-webfont.eot
     7974  2015-09-11 12:29   app/admin/fonts/dmn.svg
     5024  2015-09-11 12:29   app/admin/fonts/dmn.woff
     8100  2015-09-11 12:29   app/admin/fonts/dmn.eot
    24140  2015-09-11 12:29   app/admin/fonts/opensans-light-webfont.woff
    41280  2015-09-11 12:29   app/admin/fonts/glyphicons-halflings-regular.ttf
    45360  2015-09-11 12:29   app/admin/fonts/opensans-regular-webfont.ttf
    23320  2015-09-11 12:29   app/admin/fonts/glyphicons-halflings-regular.woff
    62926  2015-09-11 12:29   app/admin/fonts/glyphicons-halflings-regular.svg
    44556  2015-09-11 12:29   app/admin/fonts/opensans-light-webfont.ttf
    20335  2015-09-11 12:29   app/admin/fonts/glyphicons-halflings-regular.eot
    18828  2015-09-11 12:29   app/admin/fonts/opensans-regular-webfont.woff2
    21163  2015-09-11 12:29   app/admin/fonts/opensans-regular-webfont.eot
    18160  2015-09-11 12:29   app/admin/fonts/opensans-light-webfont.woff2
   115890  2015-09-11 12:29   app/admin/fonts/opensans-light-webfont.svg
   116917  2015-09-11 12:29   app/admin/fonts/opensans-bold-webfont.svg
    19516  2015-09-11 12:29   app/admin/fonts/opensans-bold-webfont.woff2
    24880  2015-09-11 12:29   app/admin/fonts/opensans-regular-webfont.woff
    25716  2015-09-11 12:29   app/admin/fonts/opensans-bold-webfont.woff
     7952  2015-09-11 12:29   app/admin/fonts/dmn.ttf
    20547  2015-09-11 12:29   app/admin/fonts/opensans-light-webfont.eot
   168464  2015-09-11 12:29   app/admin/styles/styles.css
    91393  2015-09-11 12:29   app/admin/styles/styles.css.map
      371  2015-09-11 12:29   app/admin/styles/user-styles.css
     3751  2015-09-11 12:30   app/admin/index.html
  2930662  2015-09-11 12:29   app/admin/scripts/camunda-admin-ui.js.map
   290240  2015-09-11 12:28   app/admin/scripts/deps.js
  1984533  2015-09-11 12:28   app/admin/scripts/deps.js.map
    16364  2015-09-11 12:29   app/admin/scripts/placeholders.main.js
   627127  2015-09-11 12:29   app/admin/scripts/camunda-admin-ui.js
     2909  2015-09-11 12:29   app/admin/scripts/placeholders.utils.js
      789  2015-09-11 12:29   app/admin/scripts/placeholders.jquery.js
     2424  2015-09-11 12:29   app/admin/assets/images/camunda.60.png
     2311  2015-09-11 12:29   app/admin/assets/images/camunda.72.png
     1150  2015-09-11 12:29   app/admin/assets/images/favicon.ico
     1948  2015-09-11 12:29   app/admin/assets/images/app-logo.png
     3599  2015-09-11 12:29   app/admin/assets/images/camunda.114.png
      115  2015-09-11 12:29   app/admin/assets/images/stripe.png
    16291  2015-09-11 12:29   app/tasklist/locales/en.json
    41280  2015-09-11 12:29   app/tasklist/fonts/bootstrap/glyphicons-halflings-regular.ttf
    23320  2015-09-11 12:29   app/tasklist/fonts/bootstrap/glyphicons-halflings-regular.woff
    62926  2015-09-11 12:29   app/tasklist/fonts/bootstrap/glyphicons-halflings-regular.svg
    20335  2015-09-11 12:29   app/tasklist/fonts/bootstrap/glyphicons-halflings-regular.eot
   117868  2015-09-11 12:29   app/tasklist/fonts/opensans-regular-webfont.svg
    46864  2015-09-11 12:29   app/tasklist/fonts/opensans-bold-webfont.ttf
    21925  2015-09-11 12:29   app/tasklist/fonts/opensans-bold-webfont.eot
     7974  2015-09-11 12:29   app/tasklist/fonts/dmn.svg
     5024  2015-09-11 12:29   app/tasklist/fonts/dmn.woff
     8100  2015-09-11 12:29   app/tasklist/fonts/dmn.eot
    24140  2015-09-11 12:29   app/tasklist/fonts/opensans-light-webfont.woff
    45360  2015-09-11 12:29   app/tasklist/fonts/opensans-regular-webfont.ttf
    44556  2015-09-11 12:29   app/tasklist/fonts/opensans-light-webfont.ttf
    18828  2015-09-11 12:29   app/tasklist/fonts/opensans-regular-webfont.woff2
    21163  2015-09-11 12:29   app/tasklist/fonts/opensans-regular-webfont.eot
    18160  2015-09-11 12:29   app/tasklist/fonts/opensans-light-webfont.woff2
   115890  2015-09-11 12:29   app/tasklist/fonts/opensans-light-webfont.svg
   116917  2015-09-11 12:29   app/tasklist/fonts/opensans-bold-webfont.svg
    19516  2015-09-11 12:29   app/tasklist/fonts/opensans-bold-webfont.woff2
    24880  2015-09-11 12:29   app/tasklist/fonts/opensans-regular-webfont.woff
    25716  2015-09-11 12:29   app/tasklist/fonts/opensans-bold-webfont.woff
     7952  2015-09-11 12:29   app/tasklist/fonts/dmn.ttf
    20547  2015-09-11 12:29   app/tasklist/fonts/opensans-light-webfont.eot
   201952  2015-09-11 12:29   app/tasklist/styles/styles.css
   108958  2015-09-11 12:29   app/tasklist/styles/styles.css.map
      371  2015-09-11 12:29   app/tasklist/styles/user-styles.css
     2827  2015-09-11 12:30   app/tasklist/index.html
      904  2015-09-11 12:29   app/tasklist/scripts/config.js
   782338  2015-09-11 12:29   app/tasklist/scripts/deps.js
  4424758  2015-09-11 12:29   app/tasklist/scripts/deps.js.map
   800942  2015-09-11 12:29   app/tasklist/scripts/camunda-tasklist-ui.js.map
    16364  2015-09-11 12:29   app/tasklist/scripts/placeholders.main.js
   232895  2015-09-11 12:29   app/tasklist/scripts/camunda-tasklist-ui.js
     2909  2015-09-11 12:29   app/tasklist/scripts/placeholders.utils.js
      789  2015-09-11 12:29   app/tasklist/scripts/placeholders.jquery.js
     2424  2015-09-11 12:29   app/tasklist/images/camunda.60.png
     2311  2015-09-11 12:29   app/tasklist/images/camunda.72.png
     1150  2015-09-11 12:29   app/tasklist/images/favicon.ico
      452  2015-09-11 12:29   app/tasklist/images/vendor-logo-16.png
      452  2015-09-11 12:29   app/tasklist/images/vendor-logo-20.png
     2397  2015-09-11 12:29   app/tasklist/images/app-logo.png
     2661  2015-09-11 12:29   app/tasklist/images/vendor-logo-138.png
     3599  2015-09-11 12:29   app/tasklist/images/camunda.114.png
   117868  2015-09-11 12:29   app/cockpit/fonts/opensans-regular-webfont.svg
    46864  2015-09-11 12:29   app/cockpit/fonts/opensans-bold-webfont.ttf
    21925  2015-09-11 12:29   app/cockpit/fonts/opensans-bold-webfont.eot
     7974  2015-09-11 12:29   app/cockpit/fonts/dmn.svg
    40252  2015-09-11 12:29   app/cockpit/fonts/bpmn.eot
     5024  2015-09-11 12:29   app/cockpit/fonts/dmn.woff
     8100  2015-09-11 12:29   app/cockpit/fonts/dmn.eot
    24140  2015-09-11 12:29   app/cockpit/fonts/opensans-light-webfont.woff
    41280  2015-09-11 12:29   app/cockpit/fonts/glyphicons-halflings-regular.ttf
    45360  2015-09-11 12:29   app/cockpit/fonts/opensans-regular-webfont.ttf
    23320  2015-09-11 12:29   app/cockpit/fonts/glyphicons-halflings-regular.woff
    62926  2015-09-11 12:29   app/cockpit/fonts/glyphicons-halflings-regular.svg
    44556  2015-09-11 12:29   app/cockpit/fonts/opensans-light-webfont.ttf
    13416  2015-09-11 12:29   app/cockpit/fonts/bpmn.woff
    20335  2015-09-11 12:29   app/cockpit/fonts/glyphicons-halflings-regular.eot
    18828  2015-09-11 12:29   app/cockpit/fonts/opensans-regular-webfont.woff2
    21163  2015-09-11 12:29   app/cockpit/fonts/opensans-regular-webfont.eot
    18160  2015-09-11 12:29   app/cockpit/fonts/opensans-light-webfont.woff2
   115890  2015-09-11 12:29   app/cockpit/fonts/opensans-light-webfont.svg
    40100  2015-09-11 12:29   app/cockpit/fonts/bpmn.ttf
   116917  2015-09-11 12:29   app/cockpit/fonts/opensans-bold-webfont.svg
    19516  2015-09-11 12:29   app/cockpit/fonts/opensans-bold-webfont.woff2
    24880  2015-09-11 12:29   app/cockpit/fonts/opensans-regular-webfont.woff
    25716  2015-09-11 12:29   app/cockpit/fonts/opensans-bold-webfont.woff
   131622  2015-09-11 12:29   app/cockpit/fonts/bpmn.svg
     7952  2015-09-11 12:29   app/cockpit/fonts/dmn.ttf
    20547  2015-09-11 12:29   app/cockpit/fonts/opensans-light-webfont.eot
   188544  2015-09-11 12:29   app/cockpit/styles/styles.css
   101847  2015-09-11 12:29   app/cockpit/styles/styles.css.map
      371  2015-09-11 12:29   app/cockpit/styles/user-styles.css
     3103  2015-09-11 12:30   app/cockpit/index.html
   286364  2015-09-11 12:29   app/cockpit/scripts/deps.js
  1939878  2015-09-11 12:29   app/cockpit/scripts/deps.js.map
    16364  2015-09-11 12:29   app/cockpit/scripts/placeholders.main.js
  3244037  2015-09-11 12:29   app/cockpit/scripts/camunda-cockpit-ui.js.map
   685554  2015-09-11 12:29   app/cockpit/scripts/camunda-cockpit-ui.js
     2909  2015-09-11 12:29   app/cockpit/scripts/placeholders.utils.js
      789  2015-09-11 12:29   app/cockpit/scripts/placeholders.jquery.js
     2424  2015-09-11 12:29   app/cockpit/assets/images/camunda.60.png
     2311  2015-09-11 12:29   app/cockpit/assets/images/camunda.72.png
     1150  2015-09-11 12:29   app/cockpit/assets/images/favicon.ico
     2540  2015-09-11 12:29   app/cockpit/assets/images/app-logo.png
     3599  2015-09-11 12:29   app/cockpit/assets/images/camunda.114.png
      115  2015-09-11 12:29   app/cockpit/assets/images/stripe.png
        0  2015-09-11 13:05   META-INF/maven/
        0  2015-09-11 13:05   META-INF/maven/org.camunda.bpm.webapp/
        0  2015-09-11 13:05   META-INF/maven/org.camunda.bpm.webapp/camunda-webapp-webjar/
     2682  2015-09-11 13:04   META-INF/maven/org.camunda.bpm.webapp/camunda-webapp-webjar/pom.xml
      138  2015-09-11 13:05   META-INF/maven/org.camunda.bpm.webapp/camunda-webapp-webjar/pom.properties
---------                     -------
 22453492                     174 files
```

**Comment by meyerdan** [comment]
Is that what you want?

**Comment by jangalinski** [comment]
Do you have some webapp-experts you can ask that? I am not sure what I want ... I want to include a jar in my spring-boot and have the tasklist running ... zapatas version created a much bigger (3x) jar file containing 10x the files (html) ... but these are not even contained in the webapp.war when I download and unzip it. So I am not sure, do I have to do some grunt processing of the unpacked war? Or is the current snapshot just broken?

**Comment by meyerdan** [comment]
Hi Jan,

the web jar *only* contains the web resources. But no Java classes and 
no Java libraries. I guess the reason for this is that you delete the 
WEB-INF folder?

Daniel

**Comment by jangalinski** [comment]
Hi. after some talks with Daniel and Christian about this on bpmcon I think we are good to go. I did one last fix regarding the classes-jar dependency. I thinknow  this is the webjar we need.

Christian told me that he wants to move this to distro ... I would  vote against, providing the webjar is independent of providing the distro.

**Comment by jangalinski** [comment]
Any news on this? Anything missing?

**Comment by hawky-4s-** [comment]
Hi Jan,

I had a look at the PR on the weekend. I think it would be an improvement to add the necessary maven dependencies to get the webjar running out-of-the-box like camunda-engine-rest:classes:jar and so on. So the user does not need to search and include them manually which is error-prone.
WDYT?

**Comment by jangalinski** [comment]
At least my expectation (havent tried) was that with the dependency to webapp:classes we get all deps of webapp transitive via mvn?

**Comment by hawky-4s-** [comment]
You are correct, sorry my bad.
Ok, then it looks fine!

**Comment by hawky-4s-** [comment]
Merged as 85682d2279c2fa46e6718a8bdd417dd635a4cf01

**Pull request closed without merging**
